<template>
  <QuestionTitle>Total Value Added and its share in national and agricultural GDP</QuestionTitle>
  <InfoTitle
    title="Total Value Added"
    information="
      The sum of the VA generated by all the actors operating within the value chain limits
      (i.e. actors producing, processing or channelling the value chain product) is called Direct VA,
      while the sum of the VA generated by all the suppliers external to the value chain
      (i.e. actors providing intermediate goods and services to the value chain actors, therefore not handling nor processing the value chain products)
      is called Indirect VA.<br>
      The Total Value Added is the sum of the adds up these direct and indirect components,
      revealing the overall generation of VA entailed by the value chain.
    "
  />
  <div class="flex flex-row flex-wrap justify-evenly w-full items-start my-8 gap-y-8 mb-16">
    <NiceMetric label="Total value added" :value="totalAddedValueCreators" />
    <NiceMetric
      label="Total Value Added share of national GDP"
      :value="formatPercent(+studyData.ecoData.macroData?.valueAddedShareNationalGdp)"
    />
    <NiceMetric
      label="Total Value Added share of the agricultural sector GDP"
      :value="formatPercent(+studyData.ecoData.macroData?.valueAddedShareAgriculturalGdp)"
    />
  </div>

  <QuestionTitle>How dependent is the value chain on imports?</QuestionTitle>

  <InfoTitle
    title="Rate of integration"
    information="
      The rate of integration measures the share of the intermediates consumptions (e.g. fertilizers, fuel, packaging, etc.)
      purchased by the value chain actors that are produced within the country.<br>
      The higher the share, the higher the effects of the value chain on the national economy.
    "
  />
  <HorizontalSlider
    v-if="!!studyData.ecoData.macroData?.rateOfIntegration"
    :value="studyData.ecoData.macroData?.rateOfIntegration"
    :min="0.0"
    :max="1.0"
    :labels="['0%', '100%']"
    textLeft="<b>Total value added / value of production  &lt; 70 % :</b><br>The chain depends on imports and is not well integrated into the local economy"
    textRight="<b>> 70% :</b><br> Only few goods need to be imported"
    :is-percent="true"
  />
  <div v-else class="mt-4">
    <NoDataBadge />
  </div>
  <QuestionTitle>Who <strong>creates and receives</strong> direct value added?</QuestionTitle>
  <InfoTitle
    title="Direct Value Added"
    information="
      The sum of the VA generated by all the actors operating within the value chain limits (i.e. actors producing, processing or channelling the value chain product) is called Direct VA.<br>
      It is composed of salaries and wages, land fees, royalties, financial charges (interest on loans), taxes on operations, depreciation and Net Operating Profits of the value chain direct actors.
    "
  />
  <div class="flex flex-row flex-wrap gap-y-8 justify-evenly my-12">
    <div class="flex flex-col items-center">
      <Ring
        v-if="studyData"
        :options="addedValueCreatorsRingChartData"
        style="height: 400px; width: 520px"
      />
      <div class="font-semibold">{{ totalAddedValueCreators }}</div>
    </div>
    <div class="flex flex-col items-center">
      <Ring
        v-if="studyData"
        :options="addedValueReceiversRingChartData"
        style="height: 400px; width: 520px"
      />
      <div class="font-semibold">{{ totalAddedValueReceivers }}</div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import Ring from '@charts/Ring.vue'
import { getRingChart } from '@/charts/charts.js'
import NiceMetric from '@typography/NiceMetric.vue'
import { useCurrencyUtils } from '@utils/format.js'
import { useActorsAndStages } from '@utils/misc.js'
import InfoTitle from '@typography/InfoTitle.vue'
import HorizontalSlider from '@components/charts/HorizontalSlider.vue'
import { formatPercent } from '@utils/format.js'
import QuestionTitle from '@components/study/QuestionTitle.vue'
import NoDataBadge from '@components/study/NoDataBadge.vue'

const props = defineProps({
  studyData: Object,
  currency: String
})

const { prettyAmount, convertAmount } = useCurrencyUtils(props)
const { stages, actors } = useActorsAndStages(props)

const addedValueCreatorsRingChartData = computed(() => {
  const tooltip = {}
  const items = stages.value
    .map(({ name: stageName }) => {
      const stageActors = actors.value.filter((actor) => actor.stage === stageName)

      const subTotal = convertAmount.value(
        stageActors.reduce((res, actor) => res + actor.directAddedValue, 0)
      )
      if (!isNaN(subTotal)) {
        let toolTip = `<b>${stageName}</b>: ${prettyAmount.value(subTotal)}<br>`
        for (const actor of stageActors) {
          toolTip += `<br><b>${actor.name}</b>: ${prettyAmount.value(
            convertAmount.value(actor.directAddedValue)
          )}`
        }
        tooltip[stageName] = toolTip
        return {
          value: subTotal || 0,
          name: stageName,
          label: stageName
        }
      }
    })
    .filter((item) => !!item)
    .filter((item) => item.value !== 0)

  return getRingChart(items, tooltip, 'Who creates the direct value added?')
})

function getOtherValueReceiverLabel(stageName) {
  switch (stageName) {
    case 'depreciation':
      return 'Depreciation'
    case 'employeeWages':
      return 'Workers'
    case 'financialInstitutionsInterests':
      return 'Financial Institutions'
    case 'landOwnersFees':
      return 'Landowners or Capital owners'
    case 'government':
      return 'Government'
    default:
      return stageName
  }
}

const addedValueReceiversRingChartData = computed(() => {
  const tooltip = {}

  let items = stages.value.map(({ name: stageName }) => {
    const stageActors = actors.value.filter((actor) => actor.stage === stageName)

    const subTotal = convertAmount.value(
      stageActors.reduce((res, actor) => res + actor.receivedAddedValue, 0)
    )

    let toolTip = `<b>${stageName}</b>: ${prettyAmount.value(subTotal)}<br>`
    for (const actor of stageActors) {
      toolTip += `<br><b>${actor.name}</b>: ${prettyAmount.value(
        convertAmount.value(actor.receivedAddedValue)
      )}`
    }
    tooltip[stageName] = toolTip

    return {
      value: subTotal,
      name: stageName,
      label: stageName
    }
  })
  for (let key in props.studyData.ecoData.addedValue) {
    const label = getOtherValueReceiverLabel(key)
    tooltip[key] = `<b>${label}</b>: ${prettyAmount.value(
      convertAmount.value(props.studyData.ecoData.addedValue[key])
    )}`
    if (key == 'depreciation') {
      tooltip[key] += `<br><em>Depreciation is part of the Gross Operating Profit and corresponds to renewal cost of invested capital good.
        <br>In this graph, depreciation is shown separately from Net Operating Profits of the actors.</em>`
    }
    items.push({
      value: convertAmount.value(props.studyData.ecoData.addedValue[key]),
      name: key,
      label
    })
  }

  items = items.filter((item) => !!item).filter((item) => item.value !== 0)
  return getRingChart(items, tooltip, 'Who receives the direct value added?')
})

const totalAddedValueReceivers = computed(() => {
  return prettyAmount.value(
    addedValueReceiversRingChartData.value.series[0].data.reduce((res, item) => res + item.value, 0)
  )
})

const totalAddedValueCreators = computed(() => {
  return prettyAmount.value(
    addedValueCreatorsRingChartData.value.series[0].data.reduce((res, item) => res + item.value, 0)
  )
})
</script>

<style scoped lang="scss">
</style>
